language: php

sudo: required

php:
  - 7.0
  - 7.1
  - 7.2

go:
  - 1.8

before_install:
  - composer self-update

install:
  - go get "github.com/spiral/roadrunner"
  - cp -r * $GOPATH/src/github.com/spiral/roadrunner
  - go get -u "github.com/spiral/goridge"
  - go get -u "github.com/pkg/errors"
  - go get -u "github.com/stretchr/testify/assert"
  - composer install --no-interaction --prefer-source

script:
  - go test -race -v -coverprofile=lib.txt -covermode=atomic
  - go test ./rpc -race -v -coverprofile=rpc.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash) -f lib.txt
  - bash <(curl -s https://codecov.io/bash) -f rpc.txt