language: php

sudo: required

php:
  - 7.0
  - 7.1
  - 7.2

go:
  - 1.8

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source
  - go get -u "github.com/spiral/goridge"
  - go get -u "github.com/pkg/errors"
  - go get -u "github.com/stretchr/testify/assert"

script:
  - go test -race -v