language: go

sudo: required

go:
  - "1.8"

before_install:
  - go version
  - sudo apt-get purge -y php5.6
  - sudo add-apt-repository -y ppa:ondrej/php
  - sudo apt-get update
  - sudo apt-get install -y php7.0-cli
  - php -v
  - composer self-update

install:
  - go get "github.com/spiral/roadrunner"
  - go get -u "github.com/spiral/goridge"
  - go get -u "github.com/sirupsen/logrus"
  - go get -u "github.com/pkg/errors"
  - go get -u "github.com/stretchr/testify/assert"
  - composer install --no-interaction --prefer-source

script:
  - go test -race -v -coverprofile=lib.txt -covermode=atomic
  - go test ./service -race -v -coverprofile=service.txt -covermode=atomic
  - go test ./service/rpc -race -v -coverprofile=rpc.txt -covermode=atomic
  - go test ./service/http -race -v -coverprofile=http.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash) -f lib.txt
  - bash <(curl -s https://codecov.io/bash) -f service.txt
  - bash <(curl -s https://codecov.io/bash) -f rpc.txt
  - bash <(curl -s https://codecov.io/bash) -f http.txt
