# rpc bus allows php application and external clients to talk to rr services.
rpc:
  # enable rpc server
  enable: true

  # rpc connection DSN. Supported TCP and Unix sockets.
  listen:     tcp://127.0.0.1:6001

# http service configuration.
http:
  # set to false to disable http server.
  enabled:    true

  # http host to listen.
  host:       0.0.0.0

  # http port.
  port:       8080

  # max POST request size, including file uploads.
  maxRequest: 1G

  # static file serving.
  static:
    # when true rr http will be serving static files.
    serve:  true

    # root directory for static file (http would not serve .php and .htacess files).
    root:   "/Users/wolfy-j/Projects/phpapp/webroot"

  # file upload configuration.
  uploads:
    # directory to store uploaded files before passing to PHP, keep empty to use default system
    # temp directory.
    tmpDir:

    # list of file extensions which are forbidden for uploading.
    forbid: [".php", ".exe", ".bat"]

  # http worker pool configuration.
  pool:
    # php worker command.
    command:  "php /Users/wolfy-j/Projects/phpapp/webroot/index.php rr pipes --no-ansi"

    # connection method (pipes, tcp://:9000, unix://socket.unix).
    relay:    "pipes"

    # number of active workers.
    number:   1

    # maximum jobs per worker, 0 - unlimited.
    maxJobs:  0

    # worker allocation timeouts.
    timeouts:
      # for how long socket based relay should await worker connection.
      connect:  10

      # for how long worker is allowed to be bootstrapped.
      allocate: 60

      # amount of time given to worker to gracefully destruct itself.
      destroy:  60