name: CI

on:
  push:
    branches:
    tags:
  pull_request:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.1, 7.2, 7.3, 7.4]
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Install dependencies and download binary roadrunner
      run: |
        export GO111MODULE=on
        php${{ matrix.php }} -v
        composer -V
        go mod download
        composer install --no-interaction --prefer-source
        find src/ -name "*.php" -print0 | xargs -0 -n1 -P8 php${{ matrix.php }} -l
        chmod +x bin/rr && bin/rr get-binary
